version: 2

run:
  timeout: 5m
  issues-exit-code: 1
  tests: true

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  uniq-by-line: true

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  golint:
    min-confidence: 0.8

  gofmt:
    simplify: true

  goimports:
    local-prefixes:
      - github.com/Alexander-D-Karpov/about

  gocyclo:
    min-complexity: 15

  maligned:
    suggest-new: true

  dupl:
    threshold: 100

  goconst:
    min-len: 3
    min-occurrences: 3

  misspell:
    locale: US

  lll:
    line-length: 120

  unparam:
    check-exported: false

  nakedret:
    max-func-lines: 30

  prealloc:
    simple: true
    range-loops: true
    for-loops: false

  gocritic:
    enabled-tags:
      - performance
      - style
      - experimental
    disabled-checks:
      - wrapperFunc
      - dupImport
      - ifElseChain
      - octalLiteral

linters:
  enable:
    - bodyclose
    - errcheck
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - stylecheck
    - unconvert
    - unparam
    - unused
    - whitespace

  disable:
    - gochecknoglobals

issues:
  exclude-dirs:
    - vendor
  exclude-files:
    - ".*\\.pb\\.go$"

  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - goconst

    - path: internal/plugins/
      linters:
        - dupl

    - linters:
        - lll
      source: "^//go:generate "

  exclude:
    - 'declaration of "(err|ctx)" shadows declaration at'
    - 'shadow: declaration of "err" shadows declaration'

  max-issues-per-linter: 0
  max-same-issues: 0
  new: false
